#N U M   P Y     (NUmerical PYthon)   Arrays and Vectorized Computation
 - http://docs.scipy.org/doc/numpy/user/index.html                           
 - http://www.sam.math.ethz.ch/~raoulb/teaching/PythonTutorial/intro_numpy.html

<hr>
-Fast <b>(Written in C !!!!)</b>vectorized array operations for data munging and cleaning, subsetting and   filtering, transformation, and any other kinds of computations
-Common array algorithms like sorting, unique, and set operations
- Efficient descriptive statistics and aggregating/summarizing data
- Data alignment and relational data manipulations for merging and joining together    heterogeneous data sets
- Expressing conditional logic as array expressions instead of loops with if-elifelse    branches
- Group-wise data manipulations (aggregation, transformation, function application).

##contents
- [create](#create)     [range](#range)  [indexing and slicing](#indexing)
- [assignment](#assignment)[casting](#casting) [broadcasting](#broadcasting)   [concatenate](#concatenate)  [deepcopy](#deepcopy) 
- [stats](#stats) [samples](#samples)
- [rand](#rand)
- [file](#file)

- PRODUCT scalar & arr*arr (hadamard)    

##Expressing Conditional Logic as Array Operations
In [140]: xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5]) In [141]: yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5]) In [142]: cond = np.array([True, False, True, True, False])
save u writin loop and  boos performance
uniq-->distinct



<a id="create"></a>
<hr>
## CREATE

In [2]:
import numpy as np
print('from a list')
x = np.array([1,2,3,4,5]) #Create a 1D array based on a list
print('zero  ----')
x = np.zeros(10) #Create a 1-D array of 10 zeros
x = np.zeros(10).reshape(5,2) #Create a 5 row times 2 column matrix of zeros

print('zeros_like  ---- copy from an array but set all values 0')
print(array_zeros_like)
print('one  ----')
x = np.ones([5,2]) #Create a 5 row times 2 column matrix of 1s
print('ones_like  ---- copy from an array but set all values 1')
print(array_ones_like)
array_empty = np.empty((2, 2))
print('empty  ----')
print(array_empty)
array_emptys_like = np.empty_like(tmp_ar)
print('emptys_like  ---- copy from an array but DONT set any values 1 (actually GARBAGE)')
print(array_emptys_like)
print('linespace')
print (np.linspace(0,1,4)) #Create a 1-D array from 0 to 1 included with 10 equidistant floats
x = np.linspace(0,360,90) # angle from 0 to 360 every 4 degrees
y = np.sin(x*np.pi/180) # need to convert from deg to radian



#Deciding the type of the array
#http://docs.scipy.org/doc/numpy/reference/arrays.scalars.html#arrays-scalars-built-in
data=np.zeros(( 3    # Row m
               ,3)   # Cols n
              ,dtype=int
              )
data.dtype



Creating arrays:
[ 0.          0.33333333  0.66666667  1.        ]


##describe

In [7]:
data = np.array(          #infers the data type
        [
            [6,7.5,8,0,1],
            [3,4,9,0,2]
        ]
        )
print "type" , type(data)
print "D-type" , data.dtype
print "ndim" , data.ndim
print "shape" , data.shape

type <type 'numpy.ndarray'>
D-type float64
ndim 2
shape (2, 5)


<a id="range"></a>
<hr>
###range

In [28]:
print('(start=0,stop=5,step=0.5):' + \
      ','.join(  str(x) for x in np.arange(start=0,stop=5,step=0.5)))
print('range(10):' + ','.join(str(x) for x in range(10)))
print('range(0,10,2):' + ','.join(str(x) for x in range(0,10,2)))
print('range(10,0,-2):' + ','.join(str(x) for x in range(10,0,-2)))
print("right is not INCLUDED!!!!!!!!!",range(10)

(start=0,stop=5,step=0.5):0.0,0.5,1.0,1.5,2.0,2.5,3.0,3.5,4.0,4.5
range(10):0,1,2,3,4,5,6,7,8,9
range(0,10,2):0,2,4,6,8
range(10,0,-2):10,8,6,4,2


<a id="casting"></a>
## CASTING

In [53]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
casted=numeric_strings.astype(float)#IT always generate a new array 
print('orig')
print(numeric_strings)
print('casted')
print(casted)

orig
['1.25' '-9.6' '42']
casted
[  1.25  -9.6   42.  ]


<a id="indexing"></a>
<hr>
## INDEXING and SLICING
- Indexing : single value or even a whole set of values
- Slicing  : whole rows, columns or other rectangular (hypercubic) subregions

####INDEXING

In [17]:
import numpy as np
l = np.arange(9)
arr2d = np.array([
                    [10, 20, 30], 
                    [100, 200, 300],
                    [1000, 2000, 3000]
                   ])
print "4th 3rd last",l[3], l[-2]
print "ROW 1,COLUMN 0",arr2d[1][0] #alternate syntax   :arr2d[1,0]


4th 3rd last 3 7
ROW 1,COLUMN 0 100
    Select * from T1 where rowid = yxz
[1000 2000 3000]
    Select * from T1 where rowid between 0 and K
[[10 20 30]]
    Select * from T1 where rowid between K and max
[[ 100  200  300]
 [1000 2000 3000]]
    Select  * from T1  where rowid between M and N-1
[[ 10  20  30]
 [100 200 300]]
    Select col1,col2,coln from T1 where rowid between K and max
[[ 20  30]
 [200 300]]


In [15]:
#  thea array becomes an index/rowid  to select
#  bob  -  <col1,col2,col3>
#  john -  <col1,col2,col3>
#  bob  -  <col1,col2,col3>
#  tim  -  <col1,col2,col3>
#  nick -  <col1,col2,col3>

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = arr = np.arange(start=1,stop=29,step=1 ).reshape((7, 4))

print(names)
print(data)

my_idx_keys=names == 'Bob'
print("Select * from T1 where names == Bob")
print(data[my_idx_keys])
print("Select * from T1 where names <> Bob")
print(data[-(names == 'Bob')])

print("Select * from T1 where names = bob OR  names =will")
mask = (names == 'Bob') | (names == 'Will')
print(data[mask])

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]]
Select * from T1 where names == Bob
[[ 1  2  3  4]
 [13 14 15 16]]
Select * from T1 where names <> Bob
[[ 5  6  7  8]
 [ 9 10 11 12]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]]
Select * from T1 where names = bob OR  names =will
[[ 1  2  3  4]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [25]:
print('FANCY  INDEXING ----------------')
arr = np.arange(32).reshape((8, 4))
print(arr)
print('Funny Reeordering ....')
print('   Select I1J0 from T1 UNION Select I5J3 from T1 UNION Select I7J1  from T1 UNION I1J0 Select I2J2  from T1 ')
print(arr[[1, 5, 7, 2], [0, 3, 1, 2]])
print('Select col0,col3,col1,col2 from T1 where rowid in (1,5,7,2)')
print( arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])])
print(' Keep in mind that fancy indexing, unlike slicing, always copies the data into a new array.')

FANCY  INDEXING ----------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
Funny Reeordering ....
   Select I1J0 from T1 UNION Select I5J3 from T1 UNION Select I7J1  from T1 UNION I1J0 Select I2J2  from T1 
[ 4 23 29 10]
Select col0,col3,col1,col2 from T1 where rowid in (1,5,7,2)
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]
 Keep in mind that fancy indexing, unlike slicing, always copies the data into a new array.


####SLICING

In [36]:
arr2d = np.array([
                    [1, 2, 3,4], 
                    [5, 6,7,8],
                    [9,10,11,12],
                    [13,14,15,16]
                   ])
print "ROW 1 COLUMN all",arr2d[1,:]
print "ROW 0",arr2d[0] 
print "ROWS all - COLUMN 0",arr2d[:,0:1]
print "ROWS 1,2 - COLUMN all",arr2d[1:3,:] 
print "ROW 1,2 - COLUMN 1,2",arr2d[1:3,1:3] 
print "ROW till 1 - COLUMN all",arr2d[:1]
print "ROW  from 1 - COLUMN all",arr2d[1:] 
print "ROW from0 till 2 - COLUMN all",arr2d[0:2] 
print "ROW  till 2 - COLUMN from 1",arr2d[:2, 1:]
print "---- non contigue"
print "ROW  all COLUMN 0,2,3",arr2d[:, (0,2,3)]#select col1,col9,col12
print "ROW  0 and 2 COLUMN all",arr2d[(0,2),:] 
print "ROW  0 and 1 and 2 COLUMN 0 and 1",arr2d[(0,1),(0,3)] 
#print "ROW COLUMN",arr2d[]

print "perculo",arr2d[0::,2]

ROW 1 COLUMN all [5 6 7 8]
ROW 0 [1 2 3 4]
ROWS all - COLUMN 0 [[ 1]
 [ 5]
 [ 9]
 [13]]
ROWS 1,2 - COLUMN all [[ 5  6  7  8]
 [ 9 10 11 12]]
ROW 1,2 - COLUMN 1,2 [[ 6  7]
 [10 11]]
ROW till 1 - COLUMN all [[1 2 3 4]]
ROW  from 1 - COLUMN all [[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
ROW from0 till 2 - COLUMN all [[1 2 3 4]
 [5 6 7 8]]
ROW  till 2 - COLUMN from 1 [[2 3 4]
 [6 7 8]]
---- non contigue
ROW  all COLUMN 0,2,3 [[ 1  3  4]
 [ 5  7  8]
 [ 9 11 12]
 [13 15 16]]
ROW  0 and 2 COLUMN all [[ 1  2  3  4]
 [ 9 10 11 12]]
ROW  0 and 1 and 2 COLUMN 0 and 1 [1 8]
perculo [ 3  7 11 15]


<a id="assignment"></a>
<hr>
## ASSIGNMENT

In [77]:
#Assign same value to interval
arr_assign        = np.arange(start=0,stop=10,step=1) 
arr_assign[1:5]=100
print('Assign same value to interval: ')
print(arr_assign)

#VERY IMPORTANT::: SLICES as VIEWS: Data are not copied...
print('Slices are VIEWS data are not copied: ')
orginal_array = np.arange(start=0,stop=5,step=1) 
just_a_view   = orginal_array[3:5]
just_a_view[1]=100000
print(orginal_array)
print(just_a_view)

print('Copy must be Explicit: copy() ')
a_copy=orginal_array[3:5].copy()
a_copy[1]=999
print(orginal_array)
print(a_copy)


Assign same value to interval: 
[  0 100 100 100 100   5   6   7   8   9]
Slices are VIEWS data are not copied: 
[     0      1      2      3 100000]
[     3 100000]
Copy must be Explicit: copy() 
[     0      1      2      3 100000]
[  3 999]


<a id="concatenate"></a>
<hr>
##concatenate

In [4]:
import numpy as np
x = np.array([1,2,3,4,5]) 
y = np.array([100,200,300,400,500]) 
print  np.hstack([x,y]) , "horizontally"
print  np.vstack([x,y]) , "vertically"

[  1   2   3   4   5 100 200 300 400 500] horizontally
[[  1   2   3   4   5]
 [100 200 300 400 500]] vertically


<a id="stats"></a>
## STATISTIC

In [6]:
import numpy as np
arr2d = np.array(
            [
                [1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]
            ])
print("all components SUM",arr2d.sum())
print("    cumulative  all compo SUM ")
print(arr2d.cumsum())
print("Column SUM")
print(arr2d.sum(axis=0))
print("  Cumulative Column SUM")
print(arr2d.cumsum(0))

print("Row SUM")
print(arr2d.sum(axis=1))
print("  Cumulative Row SUM")
print(arr2d.cumsum(1))


print("Mean")
print("mean",arr2d.mean())
print("mean x COLUMNS",arr2d.mean(axis=0))
print("mean x ROWS",arr2d.mean(axis=1))



print("Std")
print(arr2d.std())
print("Var")
print(arr2d.var() )
print("Min" )


x.sum() #or np.sum(x)
x.min() #or np.min(x), x.max() or np.max(x)

all components SUM
45
    cumulative  all compo SUM 
[ 1  3  6 10 15 21 28 36 45]
Column SUM
[12 15 18]
  Cumulative Column SUM
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
Row SUM
[ 6 15 24]
  Cumulative Row SUM
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]
Mean
('mean', 5.0)
('mean x COLUMNS', array([ 4.,  5.,  6.]))
('mean x ROWS', array([ 2.,  5.,  8.]))
Std
2.58198889747
Var
6.66666666667
Min
1
Max
9
argmin argmax
0
8


1

###MIN / MAX

In [8]:
print"min,max",arr2d.min(),arr2d.max(), " and relative indexes",arr2d.argmin(),arr2d.argmax()



min,max 1 9  and relative indexes 0 8


##samples
<a id="samples"></a>

In [36]:
samples = np.random.normal(size=(10))
print(samples)
samples = np.random.uniform(size=(10))
print(samples)
binomial Draw samples a binomial distribution
normal Draw samples from a normal (Gaussian) distribution
beta Draw samples from a beta distribution
chisquare Draw samples from a chi-square distribution
gamma Draw samples from a gamma distribution
uniform Draw samples from a uniform [0, 1) distribution

[ 0.11747568 -1.30176441  0.07702372 -1.11745575  0.85342322  0.09951258
  0.12625283 -0.20728576  0.96098674 -0.48822726]
[ 0.23531628  0.62871771  0.6159521   0.39539102  0.03070102  0.98375703
  0.34302233  0.19098522  0.46489593  0.11166428]


In [31]:
arr = randn(100)
print('Number of positive values', (arr > 0).sum()) 
bools = np.array([False, False, True, False])
print('bools.any() tests whether one or more values in an array is True',bools.any())
print('bools.all()  while all checks if every value is True',bools.any())



('Number of positive values', 46)
('bools.any() tests whether one or more values in an array is True', True)
('bools.all()  while all checks if every value is True', True)


<a id="rand"></a>
<hr>
# RANDOM

In [33]:
from random import normalvariate
N = 1000000
%timeit samples = [normalvariate(0, 1) for _ in xrange(N)]
%timeit np.random.normal(size=N)


1 loops, best of 3: 1.85 s per loop
10 loops, best of 3: 58.1 ms per loop


In [ ]:

seed Seed the random number generator
permutation Return a random permutation of a sequence, or return a permuted range
shuffle Randomly permute a sequence in place
rand Draw samples from a uniform distribution
randint Draw random integers from a given low-to-high range
randn Draw samples from a normal distribution with mean 0 and standard deviation 1 (MATLAB-like interface)


<a id="file"></a>
<hr>
# FILES

In [109]:
#Dump as .npy (binary format)..unuseful...
arr = np.arange(10)
#default dir C:\Users\p155121\AppData\Roaming\Enthought\Canopy\ipython_notebooks
np.save('H:\some_array', arr)

##BROADCATING
<a id="broadcasting"></a>

In [ ]:

#BROADCATING
arithmetic works between arrays of different shapes
According to the broadcasting rule, the “broadcast dimensions” must be 1 in the smaller array.
scalar cab broadcast 5*arr1
to broadcast a N-Dim u need that first dim is 1

Esempi
   to a  (3,5)   u can BROADCASTa (1,5)
    to a (7,4,9) u can BROADCASTa (1,4,9)

#CASTING to other types
float_arr = arr.astype(np.float64)
# Vector operation arr1+arr1
            
